version: "3.9"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: smart_route_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/smart_route
      - STRIPE_KEY=sk_test_...
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    container_name: smart_route_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart_route
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: smart_route_redis
    restart: always
    ports:
      - "6379:6379"

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.celery_worker", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - db
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:password@db:5432/smart_route

volumes:
  postgres_data:
